### ISSUE TITLE
Make sure to call FirebaseApp.initializeApp(Context) first.

### ISSUE THREAD

**Issue by ChrisBaker995** [hzsweers/CatchUp#66]
Hello, Why this issue appear on app lunching time?

Android studio 3.0 canary 4.  kotlin plugin Version: 1.1.2-4

```
 java.lang.RuntimeException: Unable to create application io.sweers.catchup.app.DebugCatchUpApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process io.sweers.catchup.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5793)
                                                                             at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                          Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process io.sweers.catchup.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                             at com.google.firebase.FirebaseApp.getInstance(Unknown Source:54)
                                                                             at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(Unknown Source:4)
                                                                             at io.sweers.catchup.app.ApplicationModule$Companion.provideRemoteConfig(ApplicationModule.kt:70)
                                                                             at io.sweers.catchup.app.ApplicationModule.provideRemoteConfig(Unknown Source:26)
                                                                             at io.sweers.catchup.app.ApplicationModule_ProvideRemoteConfigFactory.get(ApplicationModule_ProvideRemoteConfigFactory.java:25)
                                                                             at io.sweers.catchup.app.ApplicationModule_ProvideRemoteConfigFactory.get(ApplicationModule_ProvideRemoteConfigFactory.java:10)
                                                                             at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                             at io.sweers.catchup.app.DaggerApplicationComponent.injectCatchUpApplication(DaggerApplicationComponent.java:389)
                                                                             at io.sweers.catchup.app.DaggerApplicationComponent.inject(DaggerApplicationComponent.java:368)
                                                                             at io.sweers.catchup.app.CatchUpApplication.onCreate(CatchUpApplication.kt:64)
                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5790)
                                                                             at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                             at android.os.Looper.loop(Looper.java:164) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6540) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by hzsweers** [comment]
That's strange, it should be initialized https://github.com/hzsweers/CatchUp/blob/master/app/src/main/kotlin/io/sweers/catchup/app/ApplicationModule.kt#L69

Are you able to consistently repro it?

**Comment by ChrisBaker995** [comment]
@hzsweers I imported project as new project from github and the open it, but it's throw that error, i tried to use `getApplicationContext` but the same, maybe i should add `google.play.gms.service` because i can't find it in the `build.gradle`

**Comment by hzsweers** [comment]
I ditched that plugin because it was a pain to maintain. I stub in a bunch of fake values such that if you build without having them, it should just effectively no-op. So if you invoke FirebaseRemoteConfig.getInstance() there, it crashes?

**Comment by ChrisBaker995** [comment]
Yup i invoked it,  it's `unable to create application issue` From activity thread
![capture](https://user-images.githubusercontent.com/32912777/31743650-1cb45db4-b45c-11e7-9a0e-ac9cdc81e2f6.JPG)

**Comment by hzsweers** [comment]
strange, I thought I had that covered for unauth'd debug builds. I'll take a look soon

**Comment by Hans-Hudson** [comment]
I had this issue, try to get the latest SDK - Google Play Services
