### ISSUE TITLE
Images load too slowly on dribble, it can be done faster, see panda on iOS

### ISSUE THREAD

**Issue by hzsweers** [hzsweers/CatchUp#91]
Reported by @muandrew

#### App
```
Version: 0.1.0-80-g98e1131-dev
Version code: 906
```

#### Device details
```
Make: Google
Model: Pixel 2 XL
Resolution: 2712x1440
Density: 560dpi (560)
Release: 8.1.0
API: 27
```

![Screenshot](https://i.imgur.com/ixoZpNA.jpg)

#### Logs
```
CatchUpApplication$onCreate D Updating daynight
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
                OkHttp V --> GET https://www.reddit.com/?limit=25 h2
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25 (504ms, 19670-byte body)
ServiceController$loadData D Data load - reddit - took: 1268ms
ServiceController$loadData D Data load - hn - took: 1631ms
 AndroidFrameworkExtKt D Deleted file
 AndroidFrameworkExtKt D Deleted file
 AndroidFrameworkExtKt D Deleted file
 AndroidFrameworkExtKt D Deleted file
 AndroidFrameworkExtKt D Deleted file
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    CatchUpApplication D OnTrimMemory
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
                OkHttp V --> GET https://www.reddit.com/?limit=25 h2
ServiceController$loadData D Data load - hn - took: 358ms
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25 (343ms, 19657-byte body)
ServiceController$loadData D Data load - reddit - took: 479ms
 AndroidFrameworkExtKt D Deleted file
 AndroidFrameworkExtKt D Deleted file
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    CatchUpApplication D OnTrimMemory
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
                OkHttp V --> GET https://www.reddit.com/?limit=25 h2
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25 (435ms, 19675-byte body)
ServiceController$loadData D Data load - reddit - took: 516ms
ServiceController$loadData D Data load - hn - took: 903ms
 AndroidFrameworkExtKt D Deleted file
 AndroidFrameworkExtKt D Deleted file
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
CatchUpApplication$onCreate D Updating daynight
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
                OkHttp V --> GET https://www.reddit.com/?limit=25 h2
ServiceController$loadData D Data load - hn - took: 331ms
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25 (354ms, 19672-byte body)
ServiceController$loadData D Data load - reddit - took: 558ms
    CatchUpApplication D OnTrimMemory
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - hn - took: 74ms
ServiceController$loadData D Data load - reddit - took: 59ms
 AndroidFrameworkExtKt D Deleted file
 AndroidFrameworkExtKt D Deleted file
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    CatchUpApplication D OnTrimMemory
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
                OkHttp V --> GET https://www.reddit.com/?limit=25 h2
ServiceController$loadData D Data load - hn - took: 446ms
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25 (512ms, 19663-byte body)
ServiceController$loadData D Data load - reddit - took: 584ms
CatchUpApplication$onCreate D Updating daynight
 AndroidFrameworkExtKt D Deleted file
 AndroidFrameworkExtKt D Deleted file
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
                OkHttp V --> GET https://www.reddit.com/?limit=25 h2
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25 (416ms, 19675-byte body)
ServiceController$loadData D Data load - hn - took: 446ms
ServiceController$loadData D Data load - reddit - took: 563ms
    CatchUpApplication D OnTrimMemory
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - hn - took: 68ms
ServiceController$loadData D Data load - reddit - took: 54ms
 AndroidFrameworkExtKt D Deleted file
 AndroidFrameworkExtKt D Deleted file
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    CatchUpApplication D OnTrimMemory
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
                OkHttp V --> GET https://www.reddit.com/?limit=25 h2
ServiceController$loadData D Data load - hn - took: 328ms
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25 (352ms, 19659-byte body)
ServiceController$loadData D Data load - reddit - took: 426ms
ServiceController$loadData D Data load - hn - took: 393ms
ServiceController$loadData D Data load - hn - took: 319ms
ServiceController$loadData D Data load - hn - took: 318ms
ServiceController$loadData D Data load - hn - took: 336ms
ServiceController$loadData D Data load - hn - took: 332ms
ServiceController$loadData D Data load - hn - took: 308ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
                OkHttp V --> GET https://medium.com/browse/top?format=json h2
                OkHttp V --> GET https://api.producthunt.com/v1/posts?days_ago=0 http/1.1
                OkHttp V <-- 200 https://medium.com/browse/top?format=json (855ms, unknown-length body)
ServiceController$loadData D Data load - medium - took: 1357ms
                OkHttp V <-- 200 OK https://api.producthunt.com/v1/posts?days_ago=0 (1317ms, unknown-length body)
ServiceController$loadData D Data load - ph - took: 2053ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData E Unknown issue.
                         java.lang.IllegalStateException: Fetching first local but not first page! Received 1
                         	at io.sweers.catchup.ui.controllers.service.StorageBackedService.getPage(StorageBackedService.kt:111)
                         	at io.sweers.catchup.ui.controllers.service.StorageBackedService.getPage$default(StorageBackedService.kt:103)
                         	at io.sweers.catchup.ui.controllers.service.StorageBackedService$fetchPage$1.apply(StorageBackedService.kt:56)
                         	at io.sweers.catchup.ui.controllers.service.StorageBackedService$fetchPage$1.apply(StorageBackedService.kt:41)
                         	at io.reactivex.internal.operators.observable.ObservableConcatMapEager$ConcatMapEagerMainObserver.drain(ObservableConcatMapEager.java:267)
                         	at io.reactivex.internal.operators.observable.ObservableConcatMapEager$ConcatMapEagerMainObserver.onSubscribe(ObservableConcatMapEager.java:120)
                         	at io.reactivex.internal.operators.observable.ObservableRange.subscribeActual(ObservableRange.java:34)
                         	at io.reactivex.Observable.subscribe(Observable.java:10955)
                         	at io.reactivex.internal.operators.observable.ObservableConcatMapEager.subscribeActual(ObservableConcatMapEager.java:54)
                         	at io.reactivex.Observable.subscribe(Observable.java:10955)
                         	at io.reactivex.internal.operators.observable.ObservableReduceMaybe.subscribeActual(ObservableReduceMaybe.java:43)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
                         	at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
                         	at io.reactivex.internal.operators.maybe.MaybeFlatMapIterableObservable.subscribeActual(MaybeFlatMapIterableObservable.java:47)
                         	at io.reactivex.Observable.subscribe(Observable.java:10955)
                         	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
                         	at io.reactivex.Observable.subscribe(Observable.java:10955)
                         	at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
                         	at io.reactivex.Single.subscribe(Single.java:2779)
                         	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
                         	at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
                         	at io.reactivex.internal.operators.maybe.MaybeObserveOn.subscribeActual(MaybeObserveOn.java:38)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
                         	at io.reactivex.internal.operators.maybe.MaybeDoOnEvent.subscribeActual(MaybeDoOnEvent.java:39)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
                         	at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
                         	at io.reactivex.internal.operators.maybe.MaybeDoFinally.subscribeActual(MaybeDoFinally.java:44)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
                         	at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
                         	at com.uber.autodispose.MaybeScoper$AutoDisposeMaybe.subscribeActual(MaybeScoper.java:104)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3727)
                         	at io.reactivex.Maybe.subscribeWith(Maybe.java:3793)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3714)
                         	at io.reactivex.Maybe.subscribe(Maybe.java:3680)
                         	at com.uber.autodispose.MaybeScoper$1.subscribe(MaybeScoper.java:75)
                         	at io.sweers.catchup.ui.controllers.service.ServiceController.loadData(ServiceController.kt:395)
                         	at io.sweers.catchup.ui.controllers.service.ServiceController.loadData$default(ServiceController.kt:300)
                         	at io.sweers.catchup.ui.controllers.service.ServiceController.onAttach(ServiceController.kt:272)
                         	at com.bluelinelabs.conductor.Controller.attach(Controller.java:894)
                         	at com.bluelinelabs.conductor.Controller.access$500(Controller.java:44)
                         	at com.bluelinelabs.conductor.Controller$7.onAttached(Controller.java:1005)
                         	at com.bluelinelabs.conductor.internal.ViewAttachHandler.reportAttached(ViewAttachHandler.java:87)
                         	at com.bluelinelabs.conductor.internal.ViewAttachHandler.access$100(ViewAttachHandler.java:7)
                         	at com.bluelinelabs.conductor.internal.ViewAttachHandler$1.onAttached(ViewAttachHandler.java:47)
                         	at com.bluelinelabs.conductor.internal.ViewAttachHandler$2.onViewAttachedToWindow(ViewAttachHandler.java:126)
                         	at android.view.View.dispatchAttachedToWindow(View.java:17456)
                         	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
                         	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
                         	at android.view.ViewGroup.addViewInner(ViewGroup.java:4977)
                         	at android.view.ViewGroup.addView(ViewGroup.java:4768)
                         	at android.support.v4.view.ViewPager.addView(ViewPager.java:1479)
                         	at android.view.ViewGroup.addView(ViewGroup.java:4708)
                         	at android.view.ViewGroup.addView(ViewGroup.java:4681)
                         	at com.bluelinelabs.conductor.changehandler.SimpleSwapChangeHandler.performChange(SimpleSwapChangeHandler.java:73)
                         	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:204)
                         	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
                         	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:774)
                         	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:744)
                         	at com.bluelinelabs.conductor.Router.rebindIfNeeded(Router.java:501)
                         	at com.bluelinelabs.conductor.support.RouterPagerAdapter.instantiateItem(RouterPagerAdapter.java:77)
                         	at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1004)
                         	at android.support.v4.view.ViewPager.populate(ViewPager.java:1152)
                         	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:663)
                         	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:625)
                         	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:606)
                         	at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:2170)
                         	at android.support.design.widget.TabLayout.dispatchTabSelected(TabLayout.java:1165)
                         	at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1158)
                         	at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1128)
                         	at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1427)
                         	at android.support.design.widget.TabLayout$TabView.performClick(TabLayout.java:1537)
                         	at android.view.View$PerformClick.run(View.java:24770)
                         	at android.os.Handler.handleCallback(Handler.java:790)
                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                         	at android.os.Looper.loop(Looper.java:164)
                         	at android.app.ActivityThread.main(ActivityThread.java:6494)
                         	at java.lang.reflect.Method.invoke(Native Method)
                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                         
ServiceController$loadData D Data load - hn - took: 39ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - medium - took: 14ms
ServiceController$loadData D Data load - ph - took: 12ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - hn - took: 10ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - medium - took: 14ms
ServiceController$loadData D Data load - ph - took: 12ms
    CatchUpApplication D OnTrimMemory
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - hn - took: 13ms
                OkHttp V --> GET https://www.reddit.com/?limit=25&after=t3_7esk30 h2
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25&after=t3_7esk30 (1016ms, 13262-byte body)
ServiceController$loadData D Data load - reddit - took: 1092ms
                OkHttp V --> GET https://www.reddit.com/?limit=25&after=t3_7erj8z h2
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25&after=t3_7erj8z (687ms, 14899-byte body)
ServiceController$loadData D Data load - reddit - took: 780ms
                OkHttp V --> GET https://www.reddit.com/?limit=25&after=t3_7er78p h2
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25&after=t3_7er78p (853ms, 15577-byte body)
ServiceController$loadData D Data load - reddit - took: 923ms
                OkHttp V --> GET https://www.reddit.com/?limit=25&after=t3_7eqvac h2
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25&after=t3_7eqvac (552ms, 17931-byte body)
ServiceController$loadData D Data load - reddit - took: 701ms
                OkHttp V --> GET https://www.reddit.com/?limit=25&after=t3_7equi6 h2
                OkHttp V <-- 200 https://www.reddit.com/.json?limit=25&after=t3_7equi6 (462ms, 18452-byte body)
ServiceController$loadData D Data load - reddit - took: 605ms
    CatchUpApplication D OnTrimMemory
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.PagerController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
                OkHttp V --> POST https://api.github.com/graphql http/1.1 (890-byte body)
                OkHttp V --> GET https://api.dribbble.com/v1/shots?page=0&per_page=50 h2
                OkHttp V --> GET https://www.designernews.co/api/v2/stories?page=0 http/1.1
                OkHttp V <-- 200 OK https://www.designernews.co/api/v2/stories?page=0 (333ms, unknown-length body)
                OkHttp V --> GET https://www.designernews.co/api/v2/users/3681,79377,83292,33659,6470,55164,1959,70088,57885,77484,58922,73648,3080,12412,20780,42864,35670,3520,83076,40018,33719,33719,24829,6673,79764 http/1.1
                OkHttp V <-- 200 OK https://api.github.com/graphql (706ms, unknown-length body)
ServiceController$loadData D Data load - github - took: 1175ms
                OkHttp V <-- 200 https://api.dribbble.com/v1/shots?page=0&per_page=50 (843ms, unknown-length body)
                OkHttp V <-- 200 OK https://www.designernews.co/api/v2/users/3681,79377,83292,33659,6470,55164,1959,70088,57885,77484,58922,73648,3080,12412,20780,42864,35670,3520,83076,40018,33719,33719,24829,6673,79764 (605ms, unknown-length body)
ServiceController$loadData D Data load - dn - took: 2688ms
ServiceController$loadData D Data load - dribbble - took: 2831ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
                OkHttp V --> GET http://rss.slashdot.org/Slashdot/slashdotMainatom http/1.1
                OkHttp V <-- 200 OK http://rss.slashdot.org/Slashdot/slashdotMainatom (187ms, unknown-length body)
ServiceController$loadData D Data load - sd - took: 785ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - github - took: 5ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - sd - took: 6ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - github - took: 22ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - sd - took: 7ms
    ConductorInjection D An injector for io.sweers.catchup.ui.controllers.service.ServiceController was found in io.sweers.catchup.ui.activity.MainActivity
ServiceController$loadData D Data load - github - took: 7ms

```

**Comment by hzsweers** [comment]
This is sorta largely resolved now with the new dribbble support
