### ISSUE TITLE
Crash at launch when no API keys are setup

### ISSUE THREAD

**Issue by charlesdurham** [hzsweers/CatchUp#98]
```
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process io.sweers.catchup.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at com.google.firebase.FirebaseApp.getInstance(Unknown Source:54)
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source:0)
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at io.sweers.catchup.service.hackernews.HackerNewsModule$Companion.provideDataBase$hackernews_debug(HackerNewsService.kt:177)
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at io.sweers.catchup.service.hackernews.HackerNewsModule.provideDataBase$hackernews_debug(Unknown Source:2)
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at io.sweers.catchup.service.hackernews.HackerNewsModule_ProvideDataBase$hackernews_debugFactory.get(HackerNewsModule_ProvideDataBase$hackernews_debugFactory.java:16)
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at io.sweers.catchup.service.hackernews.HackerNewsModule_ProvideDataBase$hackernews_debugFactory.get(HackerNewsModule_ProvideDataBase$hackernews_debugFactory.java:8)
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at io.sweers.catchup.service.hackernews.HackerNewsService$fetchPage$1.subscribe(HackerNewsService.kt:74)
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at io.reactivex.Single.subscribe(Single.java:2801)
12-17 19:10:32.580 4356-4356/io.sweers.catchup.debug E/ServiceController$loadData:     at io.reactivex.internal.operators.single.SingleFlatMapIterableObservable.subscribeActual(SingleFlatMapIterableObservable.java:47)
```

If anyone just wants a quick fix remove this from `DebugCatchUpApplication`: 
```
Timber.plant(object : Tree() {
  override fun log(priority: Int, tag: String?, message: String, t: Throwable?) {
    if (priority == Log.ERROR) {
      throw RuntimeException("Timber e! Please fix:\nTag=$tag\nMessage=$message", t)
    }
  }
})
```

**Comment by hzsweers** [comment]
I think the app runs without crashing on launch now, but let me know if it doesn't!
